# Generated by Django 2.1.3 on 2018-11-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footprints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_x', models.DecimalField(decimal_places=10, default=0, help_text='Min X coordinate', max_digits=13, verbose_name='Min X')),
                ('min_y', models.DecimalField(decimal_places=10, default=0, help_text='Min Y coordinate', max_digits=13, verbose_name='Min Y')),
                ('max_x', models.DecimalField(decimal_places=10, default=0, help_text='Max X coordinate', max_digits=13, verbose_name='Max X')),
                ('max_y', models.DecimalField(decimal_places=10, default=0, help_text='Max Y coordinate', max_digits=13, verbose_name='Max Y')),
                ('path', models.CharField(default='difolt', max_length=50, verbose_name='Path')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_x', models.DecimalField(decimal_places=10, default=0, help_text='Max X coordinate', max_digits=13, verbose_name='Max X')),
                ('min_x', models.DecimalField(decimal_places=10, default=0, help_text='Min X coordinate', max_digits=13, verbose_name='Min X')),
                ('max_y', models.DecimalField(decimal_places=10, default=0, help_text='Max Y coordinate', max_digits=13, verbose_name='Max Y')),
                ('min_y', models.DecimalField(decimal_places=10, default=0, help_text='Min Y coordinate', max_digits=13, verbose_name='Min Y')),
                ('username', models.CharField(default='guest', max_length=50)),
            ],
        ),
    ]
