# Generated by Django 2.0.4 on 2018-04-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='username',
            field=models.CharField(default='guest', max_length=50),
        ),
    ]
