# Generated by Django 2.0.4 on 2018-05-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0002_position_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='footprints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_y', models.DecimalField(decimal_places=10, default=0, help_text='Min Y coordinate', max_digits=13, verbose_name='Min Y')),
                ('min_x', models.DecimalField(decimal_places=10, default=0, help_text='Min X coordinate', max_digits=13, verbose_name='Min X')),
                ('max_y', models.DecimalField(decimal_places=10, default=0, help_text='Max Y coordinate', max_digits=13, verbose_name='Max Y')),
                ('max_x', models.DecimalField(decimal_places=10, default=0, help_text='Max X coordinate', max_digits=13, verbose_name='Max X')),
                ('path', models.CharField(default='difolt', max_length=1000, verbose_name='Path')),
            ],
        ),
    ]
