# Generated by Django 2.0.4 on 2018-05-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0003_footprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='footprints',
            name='name',
            field=models.CharField(default='difolt', max_length=10, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='footprints',
            name='path',
            field=models.CharField(default='difolt', max_length=33, verbose_name='Path'),
        ),
    ]
