# Generated by Django 2.1.3 on 2019-02-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0004_auto_20180508_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='fileType',
            field=models.TextField(default='nincs', help_text='File type', max_length=50, verbose_name='File Type'),
        ),
    ]
