# Generated by Django 2.1.3 on 2019-02-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0005_position_filetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='fileType',
            field=models.CharField(default='nincs', help_text='File type', max_length=50, verbose_name='File Type'),
        ),
    ]
