# Generated by Django 2.1.3 on 2019-02-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0006_auto_20190207_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='fileType',
            field=models.CharField(default='nincs', max_length=50),
        ),
    ]
