# Generated by Django 2.1.3 on 2019-02-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0007_auto_20190207_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='fileType',
            new_name='filetype',
        ),
    ]
